---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  annotations: {}
  finalizers: []
  labels: {}
  name: "travelmgtinitiator-ballerina-conf-config-map"
  ownerReferences: []
data:
  ballerina.conf: "\nAIRLINE_HOST=\"@env:{AIRLINE_HOST}\"\nAIRLINE_PORT=\"@env:{AIRLINE_PORT}\"\
    \nHOTEL_HOST=\"@env:{HOTEL_HOST}\"\nHOTEL_PORT=\"@env:{HOTEL_PORT}\"\n"
