# Auto Generated Dockerfile

FROM ballerina/ballerina:0.970.0-alpha1
LABEL maintainer="dev@ballerina.io"

COPY ballerina_bridge.balx /home/ballerina 

EXPOSE  9090

CMD ballerina run -s ballerina_bridge.balx
