---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  annotations: {}
  finalizers: []
  labels: {}
  name: "bridgesidecar-ballerina-conf-config-map"
  ownerReferences: []
data:
  ballerina.conf: "\nPRIMARY_SERVICE_HOST=\"@env:{PRIMARY_SERVICE_HOST}\"\nPRIMARY_SERVICE_PORT=\"\
    @env:{PRIMARY_SERVICE_PORT}\"\nSIDECAR_HOST=\"@env:{SIDECAR_HOST}\"\nSIDECAR_PORT=\"\
    @env:{SIDECAR_PORT}\"\n\n[b7a.observability]\n\n[b7a.observability.metrics]\n\
    enabled=true\nprovider=\"micrometer\"\n\n[b7a.observability.metrics.micrometer]\n\
    registry.name=\"prometheus\"\n\n[b7a.observability.metrics.prometheus]\nport=9797\n\
    hostname=\"0.0.0.0\"\n\n\n[b7a.observability.tracing]\nenabled=false\nname=\"\
    jaeger\"\n\n[b7a.observability.tracing.jaeger]\nreporter.hostname=\"localhost\"\
    \nreporter.port=5775\n\n\n\n\n"
