# Auto Generated Dockerfile

FROM ballerina/ballerina:0.970.0
LABEL maintainer="dev@ballerina.io"

COPY travel_initiator.balx /home/ballerina 

EXPOSE  6060

CMD ballerina run travel_initiator.balx --config ${CONFIG_FILE} 
